/* Generated By:JavaCC: Do not edit this line. LuaParserConstants.java */
package net.blueva.luak.parser


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface LuaParserConstants {
    companion object {
        /** End of File.  */
        const val EOF: Int = 0

        /** RegularExpression Id.  */
        const val COMMENT: Int = 17

        /** RegularExpression Id.  */
        const val LONGCOMMENT0: Int = 18

        /** RegularExpression Id.  */
        const val LONGCOMMENT1: Int = 19

        /** RegularExpression Id.  */
        const val LONGCOMMENT2: Int = 20

        /** RegularExpression Id.  */
        const val LONGCOMMENT3: Int = 21

        /** RegularExpression Id.  */
        const val LONGCOMMENTN: Int = 22

        /** RegularExpression Id.  */
        const val LONGSTRING0: Int = 23

        /** RegularExpression Id.  */
        const val LONGSTRING1: Int = 24

        /** RegularExpression Id.  */
        const val LONGSTRING2: Int = 25

        /** RegularExpression Id.  */
        const val LONGSTRING3: Int = 26

        /** RegularExpression Id.  */
        const val LONGSTRINGN: Int = 27

        /** RegularExpression Id.  */
        const val AND: Int = 29

        /** RegularExpression Id.  */
        const val BREAK: Int = 30

        /** RegularExpression Id.  */
        const val DO: Int = 31

        /** RegularExpression Id.  */
        const val ELSE: Int = 32

        /** RegularExpression Id.  */
        const val ELSEIF: Int = 33

        /** RegularExpression Id.  */
        const val END: Int = 34

        /** RegularExpression Id.  */
        const val FALSE: Int = 35

        /** RegularExpression Id.  */
        const val FOR: Int = 36

        /** RegularExpression Id.  */
        const val FUNCTION: Int = 37

        /** RegularExpression Id.  */
        const val GOTO: Int = 38

        /** RegularExpression Id.  */
        const val IF: Int = 39

        /** RegularExpression Id.  */
        const val IN: Int = 40

        /** RegularExpression Id.  */
        const val LOCAL: Int = 41

        /** RegularExpression Id.  */
        const val NIL: Int = 42

        /** RegularExpression Id.  */
        const val NOT: Int = 43

        /** RegularExpression Id.  */
        const val OR: Int = 44

        /** RegularExpression Id.  */
        const val RETURN: Int = 45

        /** RegularExpression Id.  */
        const val REPEAT: Int = 46

        /** RegularExpression Id.  */
        const val THEN: Int = 47

        /** RegularExpression Id.  */
        const val TRUE: Int = 48

        /** RegularExpression Id.  */
        const val UNTIL: Int = 49

        /** RegularExpression Id.  */
        const val WHILE: Int = 50

        /** RegularExpression Id.  */
        const val NAME: Int = 51

        /** RegularExpression Id.  */
        const val NUMBER: Int = 52

        /** RegularExpression Id.  */
        const val FLOAT: Int = 53

        /** RegularExpression Id.  */
        const val FNUM: Int = 54

        /** RegularExpression Id.  */
        const val DIGIT: Int = 55

        /** RegularExpression Id.  */
        const val EXP: Int = 56

        /** RegularExpression Id.  */
        const val HEX: Int = 57

        /** RegularExpression Id.  */
        const val HEXNUM: Int = 58

        /** RegularExpression Id.  */
        const val HEXDIGIT: Int = 59

        /** RegularExpression Id.  */
        const val HEXEXP: Int = 60

        /** RegularExpression Id.  */
        const val STRING: Int = 61

        /** RegularExpression Id.  */
        const val CHARSTRING: Int = 62

        /** RegularExpression Id.  */
        const val QUOTED: Int = 63

        /** RegularExpression Id.  */
        const val DECIMAL: Int = 64

        /** RegularExpression Id.  */
        const val DBCOLON: Int = 65

        /** RegularExpression Id.  */
        const val UNICODE: Int = 66

        /** RegularExpression Id.  */
        const val CHAR: Int = 67

        /** RegularExpression Id.  */
        const val LF: Int = 68

        /** Lexical state.  */
        const val DEFAULT: Int = 0

        /** Lexical state.  */
        const val IN_COMMENT: Int = 1

        /** Lexical state.  */
        const val IN_LC0: Int = 2

        /** Lexical state.  */
        const val IN_LC1: Int = 3

        /** Lexical state.  */
        const val IN_LC2: Int = 4

        /** Lexical state.  */
        const val IN_LC3: Int = 5

        /** Lexical state.  */
        const val IN_LCN: Int = 6

        /** Lexical state.  */
        const val IN_LS0: Int = 7

        /** Lexical state.  */
        const val IN_LS1: Int = 8

        /** Lexical state.  */
        const val IN_LS2: Int = 9

        /** Lexical state.  */
        const val IN_LS3: Int = 10

        /** Lexical state.  */
        const val IN_LSN: Int = 11

        /** Literal token values.  */
        val tokenImage: Array<String?> = arrayOf<String?>(
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"--[[\"",
            "\"--[=[\"",
            "\"--[==[\"",
            "\"--[===[\"",
            "<token of kind 10>",
            "\"[[\"",
            "\"[=[\"",
            "\"[==[\"",
            "\"[===[\"",
            "<token of kind 15>",
            "\"--\"",
            "<COMMENT>",
            "\"]]\"",
            "\"]=]\"",
            "\"]==]\"",
            "\"]===]\"",
            "<LONGCOMMENTN>",
            "\"]]\"",
            "\"]=]\"",
            "\"]==]\"",
            "\"]===]\"",
            "<LONGSTRINGN>",
            "<token of kind 28>",
            "\"and\"",
            "\"break\"",
            "\"do\"",
            "\"else\"",
            "\"elseif\"",
            "\"end\"",
            "\"false\"",
            "\"for\"",
            "\"function\"",
            "\"goto\"",
            "\"if\"",
            "\"in\"",
            "\"local\"",
            "\"nil\"",
            "\"not\"",
            "\"or\"",
            "\"return\"",
            "\"repeat\"",
            "\"then\"",
            "\"true\"",
            "\"until\"",
            "\"while\"",
            "<NAME>",
            "<NUMBER>",
            "<FLOAT>",
            "<FNUM>",
            "<DIGIT>",
            "<EXP>",
            "<HEX>",
            "<HEXNUM>",
            "<HEXDIGIT>",
            "<HEXEXP>",
            "<STRING>",
            "<CHARSTRING>",
            "<QUOTED>",
            "<DECIMAL>",
            "\"::\"",
            "<UNICODE>",
            "<CHAR>",
            "<LF>",
            "\"#\"",
            "\";\"",
            "\"=\"",
            "\",\"",
            "\".\"",
            "\":\"",
            "\"(\"",
            "\")\"",
            "\"[\"",
            "\"]\"",
            "\"...\"",
            "\"{\"",
            "\"}\"",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"/\"",
            "\"^\"",
            "\"%\"",
            "\"..\"",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\"==\"",
            "\"~=\"",
        )
    }
}
